# Generated by Django 4.0 on 2021-12-21 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bairro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bairro', models.CharField(max_length=70, verbose_name='Bairro')),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_estado', models.CharField(max_length=25, verbose_name='Estado')),
                ('sigla_estado', models.CharField(max_length=2, verbose_name='Sigla do Estado')),
            ],
        ),
        migrations.CreateModel(
            name='Logradouro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logradouro', models.CharField(max_length=80, verbose_name='Logradouro')),
                ('cep', models.CharField(max_length=13, verbose_name='CEP')),
                ('bairro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.bairro')),
            ],
        ),
        migrations.CreateModel(
            name='Proprietario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_proprietario', models.CharField(max_length=55)),
                ('numero_proprietario', models.CharField(max_length=20, verbose_name='Número')),
                ('complemento_proprietario', models.CharField(max_length=40, verbose_name='Complemento')),
                ('logradouro_proprietario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.logradouro')),
            ],
        ),
        migrations.CreateModel(
            name='Terreno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inscricao', models.CharField(max_length=18, verbose_name='Inscrição imobiliária')),
                ('numero_terreno', models.CharField(max_length=20, verbose_name='Número do terreno')),
                ('complemento_terreno', models.CharField(max_length=40, verbose_name='Complemento')),
                ('lote', models.CharField(max_length=4)),
                ('quadra', models.CharField(max_length=4)),
                ('area', models.FloatField()),
                ('numero_correspondência', models.CharField(max_length=20, verbose_name='Número')),
                ('complemento_correspondência', models.CharField(max_length=40, verbose_name='Complemento')),
                ('logradouro_correspondencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='logradouro_correspondencia', to='cadastros.logradouro', verbose_name='Endereço de correspondência')),
                ('logradouro_terreno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='logradouro_terreno', to='cadastros.logradouro', verbose_name='Logradouro do terreno')),
                ('proprietario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.proprietario', verbose_name='Proprietário')),
            ],
        ),
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cidade', models.CharField(max_length=80, verbose_name='Cidade')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.estado')),
            ],
        ),
        migrations.AddField(
            model_name='bairro',
            name='cidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.cidade'),
        ),
    ]
