# Generated by Django 4.0 on 2021-12-21 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proprietario',
            name='complemento_proprietario',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Complemento'),
        ),
        migrations.AlterField(
            model_name='proprietario',
            name='numero_proprietario',
            field=models.CharField(max_length=20, null=True, verbose_name='Número'),
        ),
    ]
