# Generated by Django 4.0 on 2021-12-22 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_alter_proprietario_complemento_proprietario_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='terreno',
            old_name='complemento_correspondência',
            new_name='complemento_correspondencia',
        ),
        migrations.RenameField(
            model_name='terreno',
            old_name='numero_correspondência',
            new_name='numero_correspondencia',
        ),
    ]
