# Generated by Django 4.0 on 2021-12-27 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0004_produtividade'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtividade',
            name='pdf_teste',
            field=models.FileField(default=2, upload_to='pdf/'),
            preserve_default=False,
        ),
    ]
