# Generated by Django 4.0 on 2021-12-29 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0005_produtividade_pdf_teste'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_fiscal', models.CharField(max_length=36)),
                ('matricula_fiscal', models.CharField(max_length=5)),
                ('nivel', models.CharField(choices=[('FISCAL SANITÁRIO I', 'FISCAL SANITÁRIO I'), ('FISCAL SANITÁRIO II', 'FISCAL SANITÁRIO II')], max_length=19)),
                ('primeiro_nome', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Infracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_auto', models.DateField(verbose_name='Data da autuação')),
                ('rastreio_infracao', models.CharField(blank=True, max_length=13, null=True, verbose_name='Código de rastreio')),
                ('status_rastreio', models.CharField(blank=True, choices=[('NÃO ENVIADO AINDA', 'NÃO ENVIADO AINDA'), ('ENVIADO', 'ENVIADO'), ('ENTREGUE', 'ENTREGUE'), ('MUDOU-SE', 'MUDOU-SE'), ('ENDEREÇO INSUFICIENTE', 'ENDEREÇO INSUFICIENTE'), ('NÃO EXISTE O NÚMERO', 'NÃO EXISTE O NÚMERO'), ('DESCONHECIDO', 'DESCONHECIDO'), ('RECUSADO', 'RECUSADO'), ('OUTROS', 'OUTROS'), ('NÃO PROCURADO', 'NÃO PROCURADO'), ('AUSENTE', 'AUSENTE'), ('FALECIDO', 'FALECIDO')], max_length=22, verbose_name='Status devolução Correios')),
                ('data_entrega_autuacao', models.DateField(blank=True, null=True, verbose_name='Data da entrega do Auto de infração')),
                ('nome_recebedor', models.CharField(max_length=60, null=True, verbose_name='Quem recebeu?')),
                ('defendeu', models.CharField(choices=[('PENDENTE', 'PENDENTE'), ('SIM', 'SIM'), ('NÃO', 'NÃO')], max_length=15, verbose_name='Apresentou defesa?')),
            ],
        ),
        migrations.CreateModel(
            name='Inspecao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inspecao1', models.DateField()),
                ('horario_inspecao1', models.TimeField()),
                ('foto_inspecao_1', models.ImageField(blank=True, null=True, upload_to='')),
                ('data_relatorio1', models.DateField()),
                ('mato', models.CharField(max_length=1, null=True)),
                ('entulho', models.CharField(max_length=1, null=True)),
                ('fiscal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.fiscal')),
            ],
        ),
        migrations.CreateModel(
            name='Protocolo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocolo', models.CharField(max_length=12)),
                ('solicitante_protocolo', models.CharField(choices=[('PESSOA FÍSICA', 'PESSOA FÍSICA'), ('CORPO DE BOMBEIROS', 'CORPO DE BOMBEIROS'), ('MINISTÉRIO PÚBLICO', 'MINISTÉRIO PÚBLICO'), ('PREFEITURA', 'PREFEITURA'), ('ORDEM JUDICIAL', 'ORDEM JUDICIAL'), ('OUTRAS INSTITUIÇÕES', 'OUTRAS INSTITUIÇÕES'), ('VEREADORES', 'VEREADORES')], max_length=40)),
                ('descricao_protocolo', models.CharField(max_length=250)),
                ('ouvidoria', models.CharField(blank=True, max_length=10, null=True)),
                ('status_protocolo', models.CharField(choices=[('PENDENTE', 'PENDENTE'), ('AGUARDANDO EDITAL', 'AGUARDANDO EDITAL'), ('AGUARDANDO RETORNO DA AR', 'AGUARDANDO RETORNO DA AR'), ('FINALIZADO', 'FINALIZADO'), ('INSPECIONADO', 'INSPECIONADO'), ('PRAZO DE DEFESA AR', 'PRAZO DE DEFESA AR'), ('PRAZO DE DEFESA EDITAL', 'PRAZO DE DEFESA EDITAL'), ('PRAZO PARA JULGAMENTO AR', 'PRAZO PARA JULGAMENTO AR'), ('PRAZO DE JULGAMENTO EDITAL', 'PRAZO DE JULGAMENTO EDITAL')], max_length=26)),
                ('entrada_protocolo', models.DateField()),
                ('encerramento_protocolo', models.DateField(blank=True, null=True)),
                ('logradouro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.logradouro')),
            ],
        ),
        migrations.AlterModelOptions(
            name='estado',
            options={'ordering': ['nome_estado']},
        ),
        migrations.DeleteModel(
            name='Produtividade',
        ),
        migrations.AddField(
            model_name='inspecao',
            name='protocolo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.protocolo'),
        ),
        migrations.AddField(
            model_name='inspecao',
            name='terreno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.terreno'),
        ),
        migrations.AddField(
            model_name='infracao',
            name='inspecao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.inspecao'),
        ),
    ]
