# Generated by Django 4.0 on 2022-01-22 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0007_inspecao_carcaca_inspecao_lixo_inspecao_material_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bairro',
            options={'ordering': ['bairro']},
        ),
        migrations.AlterModelOptions(
            name='cidade',
            options={'ordering': ['nome_cidade']},
        ),
        migrations.AlterModelOptions(
            name='fiscal',
            options={'ordering': ['nome_fiscal']},
        ),
        migrations.AlterModelOptions(
            name='logradouro',
            options={'ordering': ['logradouro']},
        ),
        migrations.AlterModelOptions(
            name='proprietario',
            options={'ordering': ['nome_proprietario']},
        ),
        migrations.AlterModelOptions(
            name='protocolo',
            options={'ordering': ['protocolo']},
        ),
        migrations.AlterModelOptions(
            name='terreno',
            options={'ordering': ['inscricao']},
        ),
        migrations.AddField(
            model_name='terreno',
            name='tipo_de_imovel',
            field=models.CharField(choices=[('TERRENO', 'TERRENO'), ('CASA ABANDONADA', 'CASA ABANDONADA')], default=1, max_length=22),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inspecao',
            name='carcaca',
            field=models.CharField(blank=True, choices=[('', 'NÃO'), ('X', 'SIM')], max_length=1, null=True, verbose_name='Carcaça'),
        ),
        migrations.AlterField(
            model_name='inspecao',
            name='data_inspecao1',
            field=models.DateField(verbose_name='Data da inspeção'),
        ),
        migrations.AlterField(
            model_name='inspecao',
            name='data_relatorio1',
            field=models.DateField(verbose_name='Data do relatório da inspeção'),
        ),
        migrations.AlterField(
            model_name='inspecao',
            name='entulho',
            field=models.CharField(blank=True, choices=[('', 'NÃO'), ('X', 'SIM')], max_length=1, null=True, verbose_name='Entulho(s)'),
        ),
        migrations.AlterField(
            model_name='inspecao',
            name='foto_inspecao_1',
            field=models.FileField(upload_to='fotos/', verbose_name='Foto da inspeção'),
        ),
        migrations.AlterField(
            model_name='inspecao',
            name='horario_inspecao1',
            field=models.TimeField(verbose_name='Horário de inspeção'),
        ),
        migrations.AlterField(
            model_name='inspecao',
            name='lixo',
            field=models.CharField(blank=True, choices=[('', 'NÃO'), ('X', 'SIM')], max_length=1, null=True, verbose_name='Lixo(s)'),
        ),
        migrations.AlterField(
            model_name='inspecao',
            name='material',
            field=models.CharField(blank=True, choices=[('', 'NÃO'), ('X', 'SIM')], max_length=1, null=True, verbose_name='Material(is)'),
        ),
        migrations.AlterField(
            model_name='inspecao',
            name='mato',
            field=models.CharField(blank=True, choices=[('', 'NÃO'), ('X', 'SIM')], max_length=1, null=True, verbose_name='Mato alto'),
        ),
        migrations.AlterField(
            model_name='inspecao',
            name='movel',
            field=models.CharField(blank=True, choices=[('', 'NÃO'), ('X', 'SIM')], max_length=1, null=True, verbose_name='Móvel(is)'),
        ),
        migrations.AlterField(
            model_name='inspecao',
            name='outro',
            field=models.CharField(blank=True, choices=[('', 'NÃO'), ('X', 'SIM')], max_length=1, null=True, verbose_name='Outros'),
        ),
        migrations.AlterField(
            model_name='inspecao',
            name='pneu',
            field=models.CharField(blank=True, choices=[('', 'NÃO'), ('X', 'SIM')], max_length=1, null=True, verbose_name='Pneu(s)'),
        ),
        migrations.AlterField(
            model_name='terreno',
            name='complemento_correspondencia',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Complemento'),
        ),
        migrations.AlterField(
            model_name='terreno',
            name='complemento_terreno',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Complemento'),
        ),
    ]
