# Generated by Django 4.0 on 2022-01-22 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0008_alter_bairro_options_alter_cidade_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='infracao',
            name='numero',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='infracao',
            name='numero_format_ano',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='infracao',
            name='data_auto',
            field=models.DateField(blank=True, verbose_name='Data da autuação'),
        ),
        migrations.AlterField(
            model_name='infracao',
            name='nome_recebedor',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Quem recebeu?'),
        ),
        migrations.AlterField(
            model_name='infracao',
            name='status_rastreio',
            field=models.CharField(blank=True, choices=[('NÃO ENVIADO AINDA', 'NÃO ENVIADO AINDA'), ('ENVIADO', 'ENVIADO'), ('ENTREGUE', 'ENTREGUE'), ('MUDOU-SE', 'MUDOU-SE'), ('ENDEREÇO INSUFICIENTE', 'ENDEREÇO INSUFICIENTE'), ('NÃO EXISTE O NÚMERO', 'NÃO EXISTE O NÚMERO'), ('DESCONHECIDO', 'DESCONHECIDO'), ('RECUSADO', 'RECUSADO'), ('OUTROS', 'OUTROS'), ('NÃO PROCURADO', 'NÃO PROCURADO'), ('AUSENTE', 'AUSENTE'), ('FALECIDO', 'FALECIDO')], max_length=22, null=True, verbose_name='Status devolução Correios'),
        ),
    ]
