# Generated by Django 4.0 on 2022-01-23 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0009_infracao_numero_infracao_numero_format_ano_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infracao',
            name='data_auto',
        ),
        migrations.AddField(
            model_name='infracao',
            name='data_assinatura',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Assinatura'),
        ),
    ]
