# Generated by Django 4.0 on 2022-01-23 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0010_remove_infracao_data_auto_infracao_data_assinatura'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infracao',
            name='data_assinatura',
        ),
        migrations.AddField(
            model_name='infracao',
            name='data_auto',
            field=models.DateField(blank=True, null=True, verbose_name='Data do Auto'),
        ),
    ]
