# Generated by Django 4.0 on 2022-01-24 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0011_remove_infracao_data_assinatura_infracao_data_auto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terreno',
            name='area',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
