# Generated by Django 4.0 on 2022-01-25 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0012_alter_terreno_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='logradouro',
            name='tipo',
            field=models.CharField(choices=[('RUA', 'RUA'), ('AVENIDA', 'AVENIDA'), ('PRAÇA', 'PRAÇA'), ('BECO', 'BECO'), ('ALAMEDA', 'ALAMEDA'), ('ESTRADA', 'ESTRADA'), ('LARGO', 'LARGO'), ('PASSARELA', 'PASSARELA'), ('RODOVIA', 'RODOVIA'), ('SETOR', 'SETOR'), ('TREVO', 'TREVO'), ('TREVO', 'TREVO')], default=1, max_length=22),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='terreno',
            name='area',
            field=models.FloatField(),
        ),
    ]
