# Generated by Django 4.0 on 2022-01-26 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0013_logradouro_tipo_alter_terreno_area'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bairro',
            options={'ordering': ['nome_bairro']},
        ),
        migrations.RenameField(
            model_name='bairro',
            old_name='bairro',
            new_name='nome_bairro',
        ),
    ]
