# Generated by Django 4.0 on 2022-01-26 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0014_alter_bairro_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logradouro',
            options={'ordering': ['nome_logradouro']},
        ),
        migrations.RenameField(
            model_name='logradouro',
            old_name='logradouro',
            new_name='nome_logradouro',
        ),
    ]
