# Generated by Django 4.0 on 2022-02-11 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0017_alter_terreno_lote'),
    ]

    operations = [
        migrations.AddField(
            model_name='proprietario',
            name='nome_coresponsavel_1',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='logradouro',
            name='tipo',
            field=models.CharField(choices=[('RUA', 'RUA'), ('AVENIDA', 'AVENIDA'), ('PRAÇA', 'PRAÇA'), ('BECO', 'BECO'), ('ALAMEDA', 'ALAMEDA'), ('ESTRADA', 'ESTRADA'), ('LARGO', 'LARGO'), ('PASSAGEM', 'PASSAGEM'), ('PASSARELA', 'PASSARELA'), ('RODOVIA', 'RODOVIA'), ('SETOR', 'SETOR'), ('TRAVESSA', 'TRAVESSA'), ('TREVO', 'TREVO')], max_length=22),
        ),
    ]
