# Generated by Django 4.0 on 2022-02-11 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0018_proprietario_nome_coresponsavel_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proprietario',
            name='nome_coresponsavel_1',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
