# Generated by Django 4.0 on 2022-02-12 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0019_alter_proprietario_nome_coresponsavel_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terreno',
            name='inscricao',
            field=models.CharField(max_length=18, unique=True, verbose_name='Inscrição imobiliária'),
        ),
    ]
