# Generated by Django 4.0 on 2022-03-03 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0022_alter_infracao_defendeu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Defesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocolo', models.CharField(max_length=12)),
                ('entrada_protocolo', models.DateField(verbose_name='Data de entrada')),
                ('quem', models.CharField(max_length=100, verbose_name='Nome')),
                ('grau', models.CharField(choices=[('PROPRIO', 'PROPRIO'), ('CORRESPONSAVEL', 'CORRESPONSAVEL'), ('OUTROS', 'OUTROS')], max_length=50, verbose_name='Grau de relação')),
                ('infracao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.infracao')),
            ],
        ),
    ]
