# Generated by Django 4.0 on 2022-03-07 16:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0023_defesa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infracao',
            name='defendeu',
        ),
        migrations.AddField(
            model_name='defesa',
            name='prazo_manifesto',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Prazo de defesa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='infracao',
            name='prazo_defesa',
            field=models.DateField(blank=True, null=True, verbose_name='Prazo de defesa'),
        ),
    ]
