# Generated by Django 4.0 on 2022-03-07 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0024_remove_infracao_defendeu_defesa_prazo_manifesto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defesa',
            name='prazo_manifesto',
            field=models.DateField(blank=True, verbose_name='Prazo de defesa'),
        ),
    ]
