# Generated by Django 4.0 on 2022-03-28 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0028_infracao_data_inspecao2_infracao_data_manifesto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='infracao',
            name='data_entrega_julgamento',
            field=models.DateField(blank=True, null=True, verbose_name='Data da entrega do julgamento'),
        ),
        migrations.AddField(
            model_name='infracao',
            name='rastreio_julgamento',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='Código de rastreio do julgamento'),
        ),
        migrations.AddField(
            model_name='infracao',
            name='status_rastreio_julgamento',
            field=models.CharField(blank=True, choices=[('NÃO ENVIADO AINDA', 'NÃO ENVIADO AINDA'), ('ENVIADO', 'ENVIADO'), ('ENTREGUE', 'ENTREGUE'), ('MUDOU-SE', 'MUDOU-SE'), ('ENDEREÇO INSUFICIENTE', 'ENDEREÇO INSUFICIENTE'), ('NÃO EXISTE O NÚMERO', 'NÃO EXISTE O NÚMERO'), ('DESCONHECIDO', 'DESCONHECIDO'), ('RECUSADO', 'RECUSADO'), ('OUTROS', 'OUTROS'), ('NÃO PROCURADO', 'NÃO PROCURADO'), ('AUSENTE', 'AUSENTE'), ('FALECIDO', 'FALECIDO')], max_length=22, null=True, verbose_name='Status devolução julgamento'),
        ),
        migrations.AlterField(
            model_name='infracao',
            name='situacao',
            field=models.CharField(blank=True, choices=[('1', 'Defendeu e limpou'), ('2', 'Não defendeu e limpou'), ('3', 'Não defendeu e não limpou')], max_length=25, null=True, verbose_name='Situação'),
        ),
    ]
