# Generated by Django 4.0 on 2022-04-08 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0030_rename_protocolo_infracao_protocolo_defesa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infracao',
            name='situacao',
            field=models.CharField(blank=True, choices=[('1', 'Defendeu e limpou'), ('2', 'Não defendeu e limpou'), ('3', 'Não defendeu e não limpou'), ('4', 'Manifesto e julgamento fora do sistema'), ('5', 'Defendeu após o prazo e limpou'), ('6', 'Não recebeu e limpou')], max_length=25, null=True, verbose_name='Situação'),
        ),
    ]
