# Generated by Django 4.0 on 2022-04-08 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0031_alter_infracao_situacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infracao',
            name='situacao',
            field=models.CharField(blank=True, choices=[('1', 'Defendeu e limpou'), ('2', 'Não defendeu e limpou'), ('3', 'Não defendeu e não limpou'), ('4', 'Manifesto e julgamento fora do sistema'), ('5', 'Defendeu após o prazo e limpou'), ('6', 'Não recebeu e limpou'), ('7', 'Edital')], max_length=25, null=True, verbose_name='Situação'),
        ),
    ]
